return {
  version = "1.9",
  luaversion = "5.1",
  tiledversion = "1.9.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 5,
  nextobjectid = 21,
  properties = {
    ["light"] = "true",
    ["music"] = "mus_school",
    ["name"] = "Middle School Classroom"
  },
  tilesets = {
    {
      name = "school_interior",
      firstgid = 1,
      filename = "../tilesets/school_interior.tsx",
      exportfilename = "../tilesets/school_interior.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 1,
      name = "tiles",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 0,
        0, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 0,
        0, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 0,
        0, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 0,
        0, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 0,
        0, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 0,
        0, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 0,
        0, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 0,
        0, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 0,
        0, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          class = "",
          shape = "rectangle",
          x = 65.3333,
          y = 0,
          width = 494.667,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          class = "",
          shape = "rectangle",
          x = 564,
          y = 40,
          width = 36,
          height = 400,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          class = "",
          shape = "rectangle",
          x = 68.5,
          y = 436,
          width = 495,
          height = 44,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          class = "",
          shape = "rectangle",
          x = 40,
          y = 40,
          width = 28,
          height = 400,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          class = "",
          shape = "rectangle",
          x = 70,
          y = 40,
          width = 29,
          height = 110,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          class = "",
          shape = "rectangle",
          x = 172,
          y = 40,
          width = 392,
          height = 110,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          class = "",
          shape = "rectangle",
          x = 250,
          y = 160,
          width = 190,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          class = "",
          shape = "rectangle",
          x = 213,
          y = 231,
          width = 70,
          height = 38,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          class = "",
          shape = "rectangle",
          x = 316,
          y = 232,
          width = 69,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          class = "",
          shape = "rectangle",
          x = 415,
          y = 231,
          width = 71,
          height = 41,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          class = "",
          shape = "rectangle",
          x = 214,
          y = 291,
          width = 70,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          class = "",
          shape = "rectangle",
          x = 317,
          y = 291,
          width = 69,
          height = 37,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          class = "",
          shape = "rectangle",
          x = 416,
          y = 290,
          width = 70,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          class = "",
          shape = "rectangle",
          x = 520,
          y = 397.333,
          width = 40,
          height = 32.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          class = "",
          shape = "rectangle",
          x = 452,
          y = 120,
          width = 108,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 20,
          name = "entry",
          class = "",
          shape = "point",
          x = 133.333,
          y = 188,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 19,
          name = "transition",
          class = "",
          shape = "rectangle",
          x = 94.6667,
          y = 88,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "down",
            ["map"] = "school",
            ["marker"] = "entry4"
          }
        }
      }
    }
  }
}
